# Generated by Django 5.2.6 on 2025-09-19 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HeartRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bpm",
                    models.PositiveIntegerField(
                        help_text="Beats per minute recorded for the patient."
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the heart rate was recorded.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated.",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="The patient whose heart rate is recorded.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heart_rates",
                        to="patients.patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        help_text="User who recorded the heart rate. Can be null.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_heart_rates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Heart Rate",
                "verbose_name_plural": "Heart Rates",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
