# Generated by Django 5.2.6 on 2025-09-19 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="place",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional location associated with the patient.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patients",
                to="users.location",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="user",
            field=models.ForeignKey(
                help_text="The user responsible for this patient.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="patient",
            unique_together={("user", "first_name", "last_name", "date_of_birth")},
        ),
    ]
